apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: { { .Values.namespace.name } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: techtrends
          ports:
            - containerPort: { { .Values.containerPort } }
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: { { .Values.livenessProbe.httpGet.path } }
              port: { { .Values.containerPort } }
          readinessProbe:
            httpGet:
              path: { { .Values.readinessProbe.httpGet.path } }
              port: { { .Values.containerPort } }
